name: Docker Image CI

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" , "docker"]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push Docker images

    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push the Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:latest .
        docker push ghcr.io/${{ github.repository }}:latest

  release:
      needs: build
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      permissions:
        contents: write # Required to create a release
        packages: write # Required to push Docker images

      steps:
        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Create GitHub Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.run_number }}
            release_name: Release ${{ github.run_number }}
            body: |
              New release created by GitHub Actions.
            draft: false
            prerelease: false

        - name: Tag and push release Docker image
          run: |
            docker pull ghcr.io/${{ github.repository }}:latest
            docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:${{ github.run_number }}
            docker push ghcr.io/${{ github.repository }}:${{ github.run_number }}
